name: tripmate
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0   # ✅ Tambahkan ini agar bisa menggunakan GoogleFonts
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  intl: ^0.18.1 # atau versi terbaru


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/onboarding1.jpg
    - assets/onboarding2.jpg
    - assets/bali.jpeg
    - assets/lombok.jpeg




